server:
  servlet:
    context-path: /e-shop

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger
    operationsSorter: method
    displayRequestDuration: true

spring:
  application:
    name: eshop_api
  datasource:
    url: jdbc:mysql://${DB_HOST_DEV}:${DB_PORT_DEV}/${DB_NAME_DEV}?createDatabaseIfNotExist=true
    username: ${DB_USER_DEV}
    password: ${DB_PASSWORD_DEV}
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

cors:
  allowed-origins: ${CLIENT_URL_DEV}

logging:
  level:
    org.springframework.web: "debug"

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
